#!/bin/sh

# This is a script for installing all of the dependencies required to run a String Graph Assembly pipeline. 
# I am making this script to make setting up new virtual machines convient. These depencencies will be installed
# using the conda package manager. 

# These are are the steps for installing Miniconda for an ubuntu/debian based distro of linux.
mkdir ~/sga-assembly/install-files
cd ~/sga-assembly/install-files
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

# Now that the conda package mangager was installed now we can use it!
# We will now use conda commands to install all of the required dependencies for sga

conda install -c bioconda -y google-sparsehash 

conda install -c bioconda -y bamtools 

conda install -c conda-forge -y zlib 

conda install -c bioconda -y pysam

conda install -c bioconda -y ruffus 

# Now we will install NCBI's tools for downloading short reads. This is called the sra-tools

conda install -c bioconda -y sra-tools

# We are now all ready to run our pipeline! 
