#!/bin/sh

# This is a script for installing all of the dependencies required to run a String Graph Assembly pipeline. 
# I am making this script to make setting up new virtual machines convient. These depencencies will be installed
# using the conda package manager. 

# These are are the steps for installing Miniconda for an ubuntu/debian based distro of linux.
mkdir ~/sga-assembly/install-files
cd ~/sga-assembly/install-files
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh

# Now that the conda package mangager was installed now we can use it!
# We will now use conda commands to install all of the required dependencies for sga

conda install -c bioconda google-sparsehash 

conda install -c bioconda bamtools 

conda install -c conda-forge zlib 

conda install -c bioconda pysam

conda install -c bioconda ruffus 

# Now we will install NCBI's tools for downloading short reads. This is called the sra-tools

conda install -c bioconda sra-tools

#I am using google's cloud services so I fired up the smallest machine I could make and I started
# rolling. We will need to attach another hard drive later to store the data we are going to process.
# I tend to install the depenencies and the data on separate disks.

# Now you must create a large disk for our data (I reccomend 1TB) then we must mount the new disk and
# create a direcotory for it. You can use the instructions here to monunt the disk and creatge
# your desired directory. https://devopscube.com/mount-extra-disks-on-google-cloud/

# We are now all ready to run our pipeline! 
